name: "CI/CD: m-customer"

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main, develop, feature/#154-multi-arch-support]
    #paths:
    #  - "m-customer/**"
    #  - ".github/workflows/deploy-m-customer.yml"
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      module: m-customer
      dockerfile_path: m-customer/Dockerfile
      compose_service: m-customer
    secrets:
      ENV_IMAGE_NAME: ${{ secrets.ENV_IMAGE_NAME }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      SPRING_DATABASE_URL: ${{ secrets.SPRING_DATABASE_URL }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
